(defun color-theme-ysl ()
  "Color theme by Jianing, based off the JD Huntington's Blackboard theme"
  (interactive)
  (color-theme-install
   '(color-theme-ysl
     ((background-color . "#0C1021")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "#A7A7A7")
      (foreground-color . "#F8F8F8")
      (mouse-color . "sienna1"))
     (default ((t (:background "#0C1021" :foreground "#F8F8F8"))))
     (fringe ((t (:background "#0C1021"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "#0C1021" :foreground "#F8F8F8"))))
     (font-lock-builtin-face ((t (:foreground "#F8F8F8"))))
     (font-lock-comment-face ((t (:italic t :foreground "#AEAEAE"))))
     (font-lock-constant-face ((t (:foreground "#D8FA3C"))))
     (font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
     (font-lock-function-name-face ((t (:foreground "#FF6400"))))
     (font-lock-keyword-face ((t (:foreground "#FBDE2D"))))
     (font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))

     (font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "red"))))
     (font-lock-ysl-whitespace-face ((((class color)) (:background "grey20"))) t)
     (font-lock-ysl-line-exceed-face ((((class color)) (:background "grey20"))) t)

     (font-lock-string-face ((t (:foreground "#61CE3C"))))
     (font-lock-type-face ((t (:foreground "#8DA6CE"))))
     (font-lock-variable-name-face ((t (:foreground "#FF6400"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink"))))
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (region ((t (:background "#253B76"))))
     (mode-line ((t (:background "grey75" :foreground "black"))))
     (highlight ((t (:background "#222222"))))
     (highline-face ((t (:background "SeaGreen"))))
     (highlight-current-line-face ((t (:background "#123"))))
     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (toolbar ((t (nil))))

     (mmm-default-submode-face ((t (:background "#0C1021"))))
     (ecb-default-highlight-face ((t (:background "#253B76"))))

     (org-document-title ((((class color) (background dark)) (:foreground "orange" :weight bold :height 1.32 :family "Georgia"))))
     (org-hide (( t (:background "#0C1021" :foreground "#0C1021"))))
     (org-level-2 ((t (:inherit outline-2 :foreground "#FBDE2D"))))
     (org-level-3 ((t (:inherit outline-2 :foreground "Brown"))))
     (org-block-begin-line ((t (:underline nil :foreground "#008ED1" :background "#0C1021"))))
     (org-block-background ((t (:background "#0C1021"))))
     (org-block-end-line ((t (:overline nil :foreground "#008ED1" :background "#0C1021"))))

     (tabbar-default ((t (:background "black" :foreground "grey75"))))
     (tabbar-highlight ((t (:background "grey30" ))))
     (tabbar-unselected ((t (:inherit tabbar-default :background "black" :foreground "grey75"))))
     (tabbar-selected ((t (:inherit tabbar-default :background "#0C1021" :foreground "lightblue" :weight bold))))
     (tabbar-unselected ((t (:inherit tabbar-default))))
     (tabbar-separator ((t (:inherit tabbar-default :box (:line-width 1 :color "black" :style released-button)))))
     (zmacs-region ((t (:background "snow" :foreground "ble")))))))
